### ISSUE TITLE
"about me" and "library" buttons are removed

### ISSUE THREAD

**Issue by GOTHMONEY** [CroissantDuNord/discord-adblock#1]
Yeah, its good, however the "/* Hide the nitro ad in the profil tab*/ " removes your ability to change your about me.

( https://imgur.com/a/r7pPOcr )

EDIT: "/*Hide the nitro tab in the homepage */" removes the Library button, that some accounts have

( https://imgur.com/a/5JIvOaH )

copypasted from reddit user TobisDK

**Comment by CroissantDuNord** [comment]
Fixed, thank you to you and  TobisDK
