### ISSUE TITLE
Huge nitro add when you go over character count

### ISSUE THREAD

**Issue by DanaeStephens** [CroissantDuNord/discord-adblock#10]
So a recent update put in this huge nitro banner add that blocks 1/4 of the text box when you go over the character limit, if you guys found a way to get rid of that as well, it would be mega amazing, not that this already isn't and your work is greatly appreciated!

**Comment by CroissantDuNord** [comment]
![image](https://github.com/CroissantDuNord/discord-adblock/assets/79372025/96be0c07-a661-46d0-bf74-38d3959f845c)
This is what I could get, I'm going to push it, made the warning on the message box font smaller removed all the ads
