### ISSUE TITLE
Message requests are hidden.

### ISSUE THREAD

**Issue by Ph42oN** [CroissantDuNord/discord-adblock#12]
In direct messages, it appears below nitro and above shop if someone sends me message request. With this adblock looks like it hides message requests when it should be hiding shop, as shop appeared there when i got message request.

**Comment by CroissantDuNord** [comment]
Fixed, in last commit

**Comment by Ph42oN** [comment]
While this change fixes it while i have message request, it works incorrectly when i dont have one. In that situation, instead of hiding shop it hides first user from my direct messages.
Looking at code, it seems like it needs something else to detect what to hide. nth-of-type(3) is right when there is no message request and nth-of-type(4) is right when there is message request.

**Comment by nixRidge** [comment]
Are you able to confirm if this is still an issue? I can't reproduce this with the current rules, since we target the store and nitro tabs directly.

**Comment by Ph42oN** [comment]
Can't check it now because someone needs to send message request to see it.

**Comment by Ph42oN** [comment]
Looks like this is not happening anymore.
