### ISSUE TITLE
new ad

### ISSUE THREAD

**Issue by ac615223s5** [CroissantDuNord/discord-adblock#13]
![2023_12_08_01_03_48_Friends_Discord-1](https://github.com/CroissantDuNord/discord-adblock/assets/33037196/8f29006c-729c-4804-a3a5-4e524a879578)

![image](https://github.com/CroissantDuNord/discord-adblock/assets/33037196/dc63536f-9811-4500-8d5f-fc84dad1357c)

**Comment by RagdollClash** [comment]
It appears next to Shop in the Direct Messages menu.
![2024-01-14_09-59-50_firefox](https://github.com/CroissantDuNord/discord-adblock/assets/15317421/e06cf5dc-bde9-4b46-9fd3-77e00d160fdf)

The full HTML if you want it:
```html
<div id="popout_484" class="theme-dark layer_ec16dd" style="position: absolute; left: 312px; top: 144px;"><div class="animatorRight__5895e translate_c2f6c4 didRender_f1da13"><div><div class="content__73f32 contentNoArt__36baa"><div class="artInline_ec9433 art__91923"><img class="art_f8934e" src="/assets/b3ffe99a1e9696d82b04.png" alt=""></div><div class="body__3aff0"><h2 class="heading-md-bold__27797 defaultColor__87d87 header__7f549" style="color: white;" data-text-variant="heading-md/bold">Give the gift of style</h2><div class="text-sm-normal_e612c7" style="color: white;" data-text-variant="text-sm/normal">Check out the latest profile styles and surprise your friend with a fresh new look.</div></div><div class="buttonContainerVertical__4e562"><button type="button" class="button__2c788 button_afdfd9 lookFilled__19298 colorWhite__43488 sizeMax_ff52ba grow__4c8a4"><div class="contents_fb6220">Check it out</div></button><button type="button" class="button__2c788 button_afdfd9 lookFilled__19298 colorBrand_b2253e sizeMax_ff52ba grow__4c8a4"><div class="contents_fb6220">Maybe later</div></button></div><div class="pointer_cb5370 topLeftPointer_f6f72a"></div></div></div></div></div>
```

**Comment by RagdollClash** [comment]
Got another one booting up Discord today.
![2024-01-25_15-27-53_Discord](https://github.com/CroissantDuNord/discord-adblock/assets/15317421/0744d998-1326-446a-8d3a-e6c4c299ed01)

```html
<div id="popout_133" class="theme-dark layer_ec16dd" style="position: absolute; left: 312px; top: 124px;"><div class="animatorRight__5895e translate_c2f6c4 didRender_f1da13"><div><div class="content__73f32 contentNoArt__36baa"><div class="artInline_ec9433 art__91923"><img class="art__76661" src="/assets/90a31ceee867b0fdd8f9.png" alt=""></div><div class="body__3aff0"><h2 class="heading-md-bold__27797 defaultColor__87d87 header__7f549" data-text-variant="heading-md/bold" style="color: white;">NEW in the Shop! Cyberpunk</h2><div class="text-sm-normal_e612c7" data-text-variant="text-sm/normal" style="color: white;">The future is here, and it's looking good.</div></div><div class="buttonContainerVertical__4e562"><button type="button" class="button__2c788 button_afdfd9 lookFilled__19298 colorWhite__43488 sizeMax_ff52ba grow__4c8a4"><div class="contents_fb6220">Check it out</div></button><button type="button" class="button__2c788 button_afdfd9 lookFilled__19298 colorBrand_b2253e sizeMax_ff52ba grow__4c8a4"><div class="contents_fb6220">Maybe later</div></button></div><div class="pointer_cb5370 topLeftPointer_f6f72a"></div></div></div></div></div>
```

**Comment by nixRidge** [comment]
Thanks! Those popups really look annoying as hell.
I'm not really sure how to block these though, as I can't for the life of me get them to spawn on my client (maybe they don't show up in Europe, who knows), so I can't really make rules for these and test that they work at the same time.
Nothing really stands out to me in the HTML that would let me precisely and with certainty target these popups. If anyone's got ideas though, let me know.

**Comment by ac615223s5** [comment]
`[id^=popout]:has([class^=buttonContainerVertical]){
  display:none;
}`

**Comment by nixRidge** [comment]
Sweet, thank you! It doesn't seem to break anything on my end so I'll add the rule to our list. Keeping the issue open for a bit longer to see how it fares.

**Comment by RagdollClash** [comment]
Works well on another account.

https://github.com/CroissantDuNord/discord-adblock/assets/15317421/bc5bbd57-a254-4fea-af0d-31c3662efb70
