### ISSUE TITLE
Gift icon is back

### ISSUE THREAD

**Issue by carlmylo** [CroissantDuNord/discord-adblock#21]
Ad in Firefox:
![image](https://github.com/CroissantDuNord/discord-adblock/assets/56451149/06416d1e-ea19-43f7-a199-4ea0327c0515)

How it shows up in Vesktop:
![image](https://github.com/CroissantDuNord/discord-adblock/assets/56451149/402ddcc9-fc7f-4bd0-aa2d-f8670817f87f)

**Comment by pixelblob** [comment]
https://github.com/CroissantDuNord/discord-adblock/pull/23

**Comment by nixRidge** [comment]
I think I've solved this finally, in a way that doesn't rely on the client being set to English language. Sorry it took so long!

See: https://github.com/CroissantDuNord/discord-adblock/commit/23cb6e93f6745164b068a1ff405332a5a42438fa#diff-906db382ce57e84018c266b1e227985bfeb559de695e07bde09e68848d031481R51
