### ISSUE TITLE
Suggestion: remove "Events" button

### ISSUE THREAD

**Issue by VL4DST3R** [CroissantDuNord/discord-adblock#36]
This stupid thing has been cluttering our servers (as admins) ever since it was introduced, and nobody that I know used it more than once to see what it does, then proceed to never touch it again.

![image](https://github.com/user-attachments/assets/2d6b9c7f-6146-447b-a993-cc3872b674e8)

It would be very appreciated if you could maybe add it to the optional list of filters. I tried removing it myself but I can't get the right syntax for that element to work.

EDIT: I think I got it most of the way there:

```
li > div[class^="containerDefault_"] div[class*="link_"][class*="basicChannelRowLink_"] {
  display: none;
}
```

**Comment by nixRidge** [comment]
I will add a rule to the extras list.

Based on feedback however I might move it to a third list that focuses on removing clutter like this, as mentioned in #39

**Comment by EvanCarroll** [comment]
This was a bad idea imho. I use events on my Discord and I wasn't expecting a CSS modification called "Adblock" to remove native functionality.

**Comment by VL4DST3R** [comment]
I reckon the naming remained unchanged from its initial goal to be just an "adblock", but feature-wise It is a *very* good idea since I bet 99% of people never used this more than once on their servers. Same with other gimmick features discord pushes onto everyone that realistically only make sense in huge communities.

If you look at the main project page you will see that there are 2 patch lists: main and extra - where this rule was added to - to try to accommodate exactly this distinction between universally "bad" elements and arguably just bloat stuff like this.

**Comment by nixRidge** [comment]
Yes, furthermore, the main intention with the extra list is that you open it and select only the elements you want from it, rather than subscribing to the whole thing. I apologise if that wasn't clear.
