### ISSUE TITLE
Suggestion: Remove message forward button

### ISSUE THREAD

**Issue by VL4DST3R** [CroissantDuNord/discord-adblock#39]
Another month another discord useless feature to clutter the ui and mess with your muscle memory. A way to disable it would be appreciated maybe withing the extra adblock list. I can't seem to find the element name to attempt this myself, so I was hoping you could help.

**Comment by ftc2** [comment]
i think it's out of scope for the project, but i would actually appreciate this feature. i've almost never used the 'forward' feature, and it's always available in the dropdown menu if you need it.

currently, the forward button is on every message, and the reply button is only on other people's messages. i guess they don't think replying to your own message is common? i do it all the time...

i'd remove the forward button from all messages and ensure the reply button is visible on all messages (even your own).

**Comment by VL4DST3R** [comment]
> replying to your own message is common? i do it all the time...

Same, as for being in scope or not, there is already the extended list of blocking more "debatable" elements which some people may want to keep, so I figured this was another good candidate for that.

**Comment by ftc2** [comment]
getting rid of `Forward` is easy even if it doesn't become part of `addblock-extras.css`. try adding this to your quick css:

```css
/* Remove `Forward` hover bar button */
div[class^=hoverBarButton][aria-label=Forward] {
    display: none;
}
```

i don't think it's possible to force `Reply` into the hover bar for the user's own messages because it looks like the element's not there at all. i guess someone needs to make a vencord plugin to do that?

**Comment by VL4DST3R** [comment]
You are a saint! Adding it for my personal use.

**Comment by nixRidge** [comment]
Hiya both of you, sorry for the extended breaks from this repo, I don't get e-mail notifications about it so when I don't use Discord it just kind of fades away from my attention..

Anyways, thank you @ftc2. I cannot get the forward button to appear on my client.

The extra list was initially made for Nitro-related objects, which it is kind of already starting to go beyond. I might make an "adblock-clutter" list to get rid of clutter like the forward button and the events thing in guilds.
Any opinions on this?

**Comment by ftc2** [comment]
> You are a saint! Adding it for my personal use.

it was actually surprisingly annoying to figure it out. the damn hoverbar disappears when using the keyboard shortcut for the element picker in the dev tools. i've never had a problem like that before!

i solved it by doing `setTimeout(()=>{debugger;},5000);` and then making the hover bar appear before the 5s were up and the page froze 😉

after that, i could use the element picker on the frozen page.

**Comment by VL4DST3R** [comment]
> it was actually surprisingly annoying to figure it out. the damn hoverbar disappears when using the keyboard shortcut for the element picker in the dev tools. i've never had a problem like that before!

Trust me, *i know*. I tried doing it myself and it was a nightmare. Very clever solution there, and kinda beyond my level of experience. If you would't mind another challenge of sorts, maybe you could take a look at[ another issue i've reported](https://github.com/CroissantDuNord/discord-adblock/issues/36#event-15323270239) that I eventually managed to address myself, but I feel it's not done in the cleanest way - it seems to leave an empty element behind.

**Comment by nixRidge** [comment]
That element you might be referring to, if it's a line, is a div with the class "sectionDivider_(random string)" which I have no idea how to target properly, without potentially grabbing every sectionDivider under nav > ul :)
Would be nice to get rid of that too in any case, yah.

**Comment by ftc2** [comment]
@VL4DST3R 
> If you would't mind another challenge of sorts, maybe you could take a look at[ another issue i've reported](https://github.com/CroissantDuNord/discord-adblock/issues/36#event-15323270239) that I eventually managed to address myself, but I feel it's not done in the cleanest way - it seems to leave an empty element behind.

sure lol
https://github.com/CroissantDuNord/discord-adblock/pull/43/files#diff-f379e967a22a3a74f335f0a718715ae3232b7c3020a286e0dd6b626bfd80531eR68
