### ISSUE TITLE
Soundboard upload button missing.

### ISSUE THREAD

**Issue by pomarf** [CroissantDuNord/discord-adblock#4]
```
/* Hide nitro ad invite  */
  div.flex-2S1XBF:nth-child(4) {
    display: none; 
  }
```
 
 
 is also hiding the upload button for Discord's new soundboard option.

**Comment by CroissantDuNord** [comment]
![image](https://github.com/CroissantDuNord/discord-adblock/assets/79372025/75f5b5f6-74a6-49df-b42c-c266cb2df67f)
For me its working, you can give me screenshot ?, for more info
