### ISSUE TITLE
Suggestion: Remove "You have X days left to get a free trial of Nitro" drop-down (notice_be03aa)

### ISSUE THREAD

**Issue by Kodakami** [CroissantDuNord/discord-adblock#41]
details in title

**Comment by nixRidge** [comment]
If I ever catch it I'll try to make a rule for it. I haven't been able to get it to spawn on my client, and I need to know a bit more about where it positions itself in the code.
The string after notice_ (be03aa) is randomised, so I can't target that directly, sorry!

**Comment by nixRidge** [comment]
Got it just now, blocked it.
