### ISSUE TITLE
Profile Shop tab still there

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [CroissantDuNord/discord-adblock#9]
![image](https://github.com/CroissantDuNord/discord-adblock/assets/138950887/1703e059-a569-4ecd-b70a-4c6e1b440183)

**Comment by steenburgh** [comment]
I also don't see this on my profile page

**Comment by CroissantDuNord** [comment]
I just tried to block everything in the class before this ad. It currently work, i hope it will still when new ad banner come out (it should), For now im gonna close this issue
